# Generated by Django 5.2.9 on 2025-12-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='follower',
        ),
    ]
